_BASE_: "../Base-RCNN-FPN.yaml"
EXPERIMENT_NAME: ""
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LGZ_v8_300arcsec/LGZ_COCOstyle/annotations/"
DATALOADER:
  NUM_WORKERS: 1
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
  IMAGE_DIR: "/data/mostertrij/data/frcnn_images/"
INPUT:
  SCALE_FACTOR: 1.5037593984962405 
  MIN_SIZE_TRAIN: (200,)
  MIN_SIZE_TEST: 200
  MAX_SIZE_TRAIN: 200
  MAX_SIZE_TEST: 200
MODEL:
  MASK_ON: False
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  # Determine mean of our GBR channels
  #PIXEL_MEAN: [242.868, 246.401, 246.283]
  #PIXEL_STD: [52.314, 15.5175, 44.389]
  PIXEL_MEAN: [246.76874, 239.2626,  249.68981] 
  PIXEL_STD: [12.0407, 8.531488, 10.88658]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  BACKBONE:
      # Remove StopGrad at a specified stage so that no bottom layers are frozen
      # Default value is 2
      FREEZE_AT: -1
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[0.333, 0.5, 1.0, 2.0, 3.0]]
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512   # faster, and good enough for this toy dataset (default: 512)
    NUM_CLASSES: 1  # only has one class (radio_source)
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  BASE_LR: 0.0003
  IMS_PER_BATCH: 4
  STEPS: ()
  MAX_ITER: 100000 
  CHECKPOINT_PERIOD: 30000
TEST:
  EVAL_PERIOD: 20000
