_BASE_: "base_lofar_fast_rcnn.yaml"
OUTPUT_DIR: "/data/mostertrij/tridentnet/output/LB300_precomputed_withRot_constantLR/"
DATASET_PATH: "/data/mostertrij/data/frcnn_images/LB300_precomputed/LGZ_COCOstyle/annotations/"
DATASETS:
  TRAIN: ("train",)
  TEST: ("train","val","test")
INPUT:
  ROTATION_ENABLED: True
SOLVER:
  #LR_SCHEDULER_NAME:  "WarmupCosineLR" 
  STEPS: ()
  MAX_ITER: 100000 
  CHECKPOINT_PERIOD: 10000
TEST:
  REMOVE_UNRESOLVED: False
  EVAL_PERIOD: 10000
  EXTRA_EVAL: [1,500,1000,5000]
